---
# tasks file for storage
- name: Update APT package index
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install nfs-common package
  apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point directories
  file:
    path: "{{ item.mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  loop: "{{ shared_storage }}"

- name: Add NFS mounts to /etc/fstab
  mount:
    name: "{{ item.mount_point }}"
    src: "{{ item.nfs_server }}"
    fstype: nfs
    opts: defaults
    state: present
  loop: "{{ shared_storage }}"

- name: Mount all NFS shares
  mount:
    src: "{{ item.nfs_server }}"
    path: "{{ item.mount_point }}"
    opts: rw,sync,hard
    state: mounted
    fstype: nfs
  loop: "{{ shared_storage }}"
  # notify: Move User's home directory