- name: Install prerequisites for all
  hosts: controller_node_group, worker_node_group, login_node_group
  roles:
    - role: passwordless
    - role: munge
    - role: slurm
# - import_playbook: worker.yml
# - import_playbook: controller.yml
# - import_playbook: login.yml